### ISSUE TITLE
Небольшая проблема с модом.

### ISSUE THREAD

**Issue by Diablolend** [Bogdan-G/FFoKC#7]
Приветствую. Не так давно перешёл на данный форк. Сегодня же столкнулся с такой проблемой, что при ношении квантовой брони, выдаёт нижеприведённую ошибку, и более того, квант становится простой тряпкой, будто и без брони вовсе.
Сразу стоит оговорить то, что на неофициальном релизе KCauldron 1614, такой ошибки нет.

Очень буду благодарен, если есть возможность фикса.

industrialcraft-2-2.2.827-experimental

[Server thread/WARN]: Detected invalid armor damage application:
java.lang.Throwable
	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
	at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:248) [add.class:?]
	at net.minecraft.item.ItemStack.isDamaged(ItemStack.java:316) [add.class:?]
	at net.minecraft.item.ItemStack.func_77972_a(ItemStack.java:327) [add.class:?]
	at net.minecraftforge.common.ISpecialArmor$ArmorProperties.ApplyArmor(ISpecialArmor.java:164) [ISpecialArmor$ArmorProperties.class:1.7.10-0.test25]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1402) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1245) [yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:903) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1158) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.localAttackEntityFrom(EntityPlayerMP.java:646) [mw.class:?]
	at api.player.server.ServerPlayerBase.attackEntityFrom(Unknown Source) [ServerPlayerBase.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerBaseMP.attackEntityFrom(GCPlayerBaseMP.java:72) [GCPlayerBaseMP.class:?]
	at api.player.server.ServerPlayerAPI.attackEntityFrom(Unknown Source) [ServerPlayerAPI.class:?]
	at api.player.server.ServerPlayerAPI.attackEntityFrom(Unknown Source) [ServerPlayerAPI.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java) [mw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:143) [yg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70785_a(EntityMob.java:177) [yg.class:?]
	at net.minecraft.entity.monster.EntitySpider.func_70785_a(EntitySpider.java:129) [yn.class:?]
	at net.minecraft.entity.EntityCreature.func_70626_be(EntityCreature.java:95) [td.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2072) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) [sw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36) [yg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899) [sv.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) [sw.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41) [yg.class:?]
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(EntitySpider.java:37) [yn.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:2666) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) [mt.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2618) [ahb.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2423) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Bogdan-G** [comment]
привет, был фикс, если ядро, 34.71, или скомпилированное из исходников, вроде там нет этой ошибки. Ошибка была в изменении вроде instanceof на getClass().equals() в форге.

**Comment by Diablolend** [comment]
Приветствую ещё раз. Поставил самое последнее ядро FFoKC-1.7.10-0.test34.71-server.jar
Ошибка в нём как раз и была замечена впервые.  

Из исходников собрать не могу:
java.io.IOException: Server returned HTTP response code: 401 for URL: http://ci.jenkins.minecraftforge.net/job/FFoKC/api/python?tree=allBuilds[result,number,actions[text],changeSet[items[author[fullName],comment]]]

**Comment by Bogdan-G** [comment]
это уже делали? https://github.com/Bogdan-G/FFoKC/issues/4#issuecomment-379112175
если патч применился, то файл будет в build/distributions, писать что build successful не будет (если собирать через консоль). Если есть падение при работе ивента галактикрафта то перенести изменение в ядро, его ASM правка может не состыковаться.

**Comment by Diablolend** [comment]
Получилось пропатчить, так сказать, невероятным чудом.

Но случился сбой:
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Или же я не так всё сделал.

**Comment by Bogdan-G** [comment]
такое сообщение нормально, я поэтому и написал. Теперь забираем файл build/distributions, и все гг.

**Comment by Diablolend** [comment]
Забрал, поставил и запустил.

Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
2019-04-10 12:26:43,822 ERROR RollingRandomAccessFile contains an invalid element or attribute "bufferSize"
2019-04-10 12:26:44,938 ERROR RollingRandomAccessFile contains an invalid element or attribute "bufferSize"
2019-04-10 12:26:49,051 ERROR RollingRandomAccessFile contains an invalid element or attribute "bufferSize"
2019-04-10 12:26:55,529 ERROR RollingRandomAccessFile contains an invalid element or attribute "bufferSize"

**Comment by Bogdan-G** [comment]
проигнорировать можно

**Comment by Diablolend** [comment]
Я бы с радостью. Но после последнего сообщения он запускает интерфейс ванильного сервера и после чего просто крашится.

Как же сложно собирааать. >_<

**Comment by Bogdan-G** [comment]
О_о он выпилен типо, откуда там ему взяться, была какая то команда без gui запускать.
